### ISSUE TITLE
Example doesn't compile with MSVC (anymore)

### ISSUE THREAD

**Issue by Caball009** [j8asic/SpeciaLUT#4]
The example doesn't seem to compile anymore with the latest MSVC compiler. It used to compile correctly. I tried with older versions of the code as well as some older compiler versions, but couldn't find a working combination anymore.

A fix would be appreciate: https://godbolt.org/z/nMdMv4bsx

**Comment by j8asic** [comment]
I fixed unsigned/signed bug: 8425fc3ba11c716f2dd8f8cf4b011fa7abbaea01
Seems that MSVC is stupid to auto deduce constexpr stuff, so you must be explicit about it: 1135d1ce4e005665ff94068b25455adca63f0419

Thanks for testing this out!
